### PR TITLE
Initial commit of Jekyll site

### PR DESCRIPTION
**Pull request by cweagans**
Using the Hyde theme for now. Maybe we can find a designer that would be willing to do the design for us.

### CODE REVIEW

**Comment by ffes** [comment]
Looks nice. On my netbook with a small screen the div on the left is a bit too small, so the large "Universal Ctags" text not entirely visible. Bit for now it will do.

We need a "logo" and our own favicon, but that can also be done later. I have a "how to test local" document on another machine ready. Will submit a PR for that.

**Comment by ffes** [comment]
@masatake Do you want to look at this before merging or shall we just merge and go from there?

**Comment by ffes** [comment]
The LICENSE.md seems to be the license of the hyde theme, and not necessarily the license to our site. Any thoughts on that?

**Comment by masatake** [comment]
@ffes, please merge. I cannot find the time to see all.

**Comment by cweagans** [comment]
I don't want any trouble with having to relicense the Hyde theme files. Probably best to just go with MIT, though we could probably license the content as creative commons or something.

**Comment by cweagans** [comment]
For the record, I don't have merge access here either.

**Comment by ffes** [comment]
@cweagans I will add the developers to this repo as well.

**Comment by cweagans** [comment]
:+1:

**Pull request merged**
