### PR TITLE
Blog post about snaps having a maintainer & fixes.

### PR DESCRIPTION
**Pull request by tartley**
I now think the snap is in a state that is viable for daily use (and am using it daily myself.)

There are still a bunch of things to fix, and I'll keep on working on them, but I think it's now reasonable to make a post to promote snaps.

### CODE REVIEW

**Comment by masatake** [comment]
Where can I read this blog as a web page?
I would like to know its URL.

**Comment by k-takata** [comment]
It should be shown under https://ctags.io/blog/.

**Comment by masatake** [comment]
@k-takata, thank you.
The URL you showed is applicable to universal-ctags/universal-ctags.github.io ?

**Comment by k-takata** [comment]
E.g.
https://github.com/universal-ctags/universal-ctags.github.io/blob/master/_posts/2015-06-06-new-website.md is shown as https://ctags.io/2015/06/06/new-website/ .
(This is the only one post currently available, though.)

**Comment by masatake** [comment]
Oh, I see.

**Comment by masatake** [comment]
@tartley, I invited you to "ctags-blog-authors" team.
If you are o.k., please, accept the invitation and merge your change by yourself.

**Comment by k-takata** [comment]
I merge this.

**Pull request merged**
